SESSI/Models/HomeGallery.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SESSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeGallery
    {
        public int ID { get; set; }
        public string ImagePath { get; set; }
    }
}

SESSI/Controllers/HomeBannersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SESSI.Models;
using SESSI.ViewModel;

namespace SESSI.Controllers
{
    public class HomeBannersController : Controller
    {
        private DatabaseOfSessiEntities1 db = new DatabaseOfSessiEntities1();
        HomeBanner t1 = new HomeBanner();
        // GET: HomeBanners


        public List<HomeBanner> HomeBannerList()
        {
            var Image = db.HomeBanners.ToList();
            return Image;
        }

        public ActionResult Index()
        {
            MergeHome obj = new MergeHome();
            obj.MergeHomeBanner = HomeBannerList();
            return View(obj);
        }


     
     
        // GET: HomeBanners/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HomeBanner homeBanner = db.HomeBanners.Find(id);
            if (homeBanner == null)
            {
                return HttpNotFound();
            }
            return View(homeBanner);
        }

        // GET: HomeBanners/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeBanners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HomeBanner homeBanner, HttpPostedFileBase ImagePath)
        {


            if (ModelState.IsValid)
            {
                string ImageName = Path.GetFileName(ImagePath.FileName);
                string Image = Server.MapPath(@"\Images\" + ImageName);
                ImagePath.SaveAs(Image);
                t1.ImagePath = (@"\Images\" + ImageName);
               db.HomeBanners.Add(t1);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(t1);
        }

        // GET: HomeBanners/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HomeBanner homeBanner = db.HomeBanners.Find(id);
            if (homeBanner == null)
            {
                return HttpNotFound();
            }
            return View(homeBanner);
        }

        // POST: HomeBanners/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ImagePath")] HomeBanner homeBanner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(homeBanner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(homeBanner);
        }

        // GET: HomeBanners/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HomeBanner homeBanner = db.HomeBanners.Find(id);
            if (homeBanner == null)
            {
                return HttpNotFound();
            }
            return View(homeBanner);
        }

        // POST: HomeBanners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HomeBanner homeBanner = db.HomeBanners.Find(id);
            db.HomeBanners.Remove(homeBanner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SESSI/Controllers/HomeGalleriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SESSI.Models;
using SESSI.ViewModel;
namespace SESSI.Controllers
{
    public class HomeGalleriesController : Controller
    {
        private DatabaseOfSessiEntities1 db = new DatabaseOfSessiEntities1();
        public HomeGallery DataObject = new HomeGallery();
        // GET: HomeGalleries




        public List<HomeGallery> HomeGalleryList()
        {
            var image = db.HomeGalleries.ToList();
            return image;
        }




        public ActionResult Index()
        {
            return View(db.HomeGalleries.ToList());

        }
  






        // GET: HomeGalleries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HomeGallery homeGallery = db.HomeGalleries.Find(id);
            if (homeGallery == null)
            {
                return HttpNotFound();
            }
            return View(homeGallery);
        }

        // GET: HomeGalleries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeGalleries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HomeGallery homeGallery, HttpPostedFileBase ImagePath)
        {
            if (ModelState.IsValid)
            {
                string ImageName = Path.GetFileName(ImagePath.FileName);
                string Image = Server.MapPath(@"\Images\" + ImageName);
                ImagePath.SaveAs(Image);
                DataObject.ImagePath = (@"\Images\" + ImageName);
                db.HomeGalleries.Add(DataObject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(DataObject);
        }

        // GET: HomeGalleries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HomeGallery homeGallery = db.HomeGalleries.Find(id);
            if (homeGallery == null)
            {
                return HttpNotFound();
            }
            return View(homeGallery);
        }

        // POST: HomeGalleries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ImagePath")] HomeGallery homeGallery)
        {
            if (ModelState.IsValid)
            {
                db.Entry(homeGallery).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(homeGallery);
        }

        // GET: HomeGalleries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HomeGallery homeGallery = db.HomeGalleries.Find(id);
            if (homeGallery == null)
            {
                return HttpNotFound();
            }
            return View(homeGallery);
        }

        // POST: HomeGalleries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HomeGallery homeGallery = db.HomeGalleries.Find(id);
            db.HomeGalleries.Remove(homeGallery);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SESSI/Views/HomeGalleries/Create.cshtml
@model SESSI.Models.HomeGallery

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Dashboard.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "HomeBanners", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Gallery</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" class="form-control" name="ImagePath" />
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="~/HomeGalleries/Index" style="color:seagreen">BACK TO LIST</a>
</div>

SESSI/Views/HomeGalleries/Delete.cshtml
@model SESSI.Models.HomeGallery

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Dashboard.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HomeGallery</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-default" /> |
    <a href="~/HomeGalleries/Index" style="color:seagreen">BACK TO LIST</a>
</div>
    }
</div>

SESSI/Views/HomeGalleries/Details.cshtml
@model SESSI.Models.HomeGallery

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Dashboard.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Gallery</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>
</div>
<p>
    <a href="~/HomeGalleries/Edit/@Model.ID" style="color:seagreen">EDIT</a> |
    <a href="~/HomeGalleries/Index" style="color:seagreen">BACK TO LIST</a>
</p>

SESSI/Views/HomeGalleries/Edit.cshtml
@model SESSI.Models.HomeGallery

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Dashboard.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gallery</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" class="form-control" name="ImagePath" />
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="~/HomeGalleries/Index" style="color:seagreen">BACK TO LIST</a>
</div>

SESSI/Views/HomeGalleries/Index.cshtml
@model IEnumerable<SESSI.Models.HomeGallery>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Dashboard.cshtml";
}
<br />
<div class="h4 text-center" style="color:seagreen">HOME GALLERY</div>
<p>
    <a href="~/HomeGalleries/Create" style="color:seagreen">CREATE NEW</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ImagePath)
        </td>
        <td>
            <a href="~/HomeGalleries/Edit/@item.ID" style="color:seagreen">EDIT</a> |
            <a href="~/HomeGalleries/Details/@item.ID" style="color:seagreen">DETAILS</a> |
            <a href="~/HomeGalleries/Delete/@item.ID" style="color:seagreen">DELETE</a>
        </td>
    </tr>
}

</table>